### ISSUE TITLE
Add a semi transparent background behind item name plates

### ISSUE THREAD

**Issue by Scellow** [nusku-co/conquergods#10]
I'm not sure if it is possible, but adding a semi transparent background behind the name plates of items would help a lot with visibility

In some cases it is hard to know what is what 

Here is how it's done in Diablo:

![image](https://user-images.githubusercontent.com/27389256/35219025-1cf77918-ff71-11e7-86fa-75fec91bdae9.png)

**Comment by nusku-co** [comment]
I was actually thinking of this too since item quality is now showing, it makes it a bit hard to see.
