### ISSUE TITLE
Someone uses Roar while you can activate Superman removes the possibility to activate it

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#135]
1. Wait for XP to go to max.
2. XP skills pops (you can activate them)
3. Someone else uses Roar
4. You can no longer activate XP skills

**Comment by nusku-co** [comment]
I tried replicating this but I wasn't able to. I use Roar as the other character already had XP up and I was still able to use Superman.

Could you see if you can replicate it again?

**Comment by prinya801** [comment]
Not really sure but I was plvling a friend and he used Roar just as Superman popped and he removed my Superman.
