### ISSUE TITLE
Using Superman retains the attack speed even after it has worn off

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#156]
If you keep attacking the same mob. In training grounds for example.

**Comment by bominajey** [comment]
![image](https://user-images.githubusercontent.com/29521072/36052041-7067d3ac-0dec-11e8-9280-1dd1eea3e586.png)

**Comment by prinya801** [comment]
https://i.imgur.com/abYL9Xp.gifv

**Comment by nusku-co** [comment]
This is actually how it should work - I recently added this change in a recent update. If you keep attacking the target and an effect/transformation ends, you retain the attack speed or attack range you had

**Comment by prinya801** [comment]
Sounds pretty weird, Superman OP in training grounds then.

**Comment by nusku-co** [comment]
Yeap, same with Robot (for hitting 2 stakes) and Cyclone for the attack speed
