### ISSUE TITLE
Mobs not enough present on important spots

### ISSUE THREAD

**Issue by Scellow** [nusku-co/conquergods#16]
This place for example used to be good to farm 

![image](https://user-images.githubusercontent.com/27389256/35220305-1e94c47e-ff76-11e7-97ae-dae9bf642037.png)

**Comment by nusku-co** [comment]
The spawns have been taking from version CO version 4351, and should be as they were in that version. I'll take a look on the earliest binary I can find to see what this spawn looks like on there

**Comment by Scellow** [comment]
I think you are right, i was playing the french version, i'm not sure they had this version

**Comment by nusku-co** [comment]
As for next update, I have temporarily increased monster spawns globally by 50% to see what they would look like.
Ideally for release they would need to be manually fine tuned, not globally increased

**Comment by nusku-co** [comment]
I am closing this for now. I will re-visit this once we go-live.
