### ISSUE TITLE
Equipment not dropped if killed by player while having a Red name

### ISSUE THREAD

**Issue by Scellow** [nusku-co/conquergods#197]
1: 
![conquer_2018-02-15_13-44-10](https://user-images.githubusercontent.com/27389256/36257290-8d3de4da-1256-11e8-9d03-87186be1d8bd.jpg)

2:
![conquer_2018-02-15_13-44-26](https://user-images.githubusercontent.com/27389256/36257293-910037e4-1256-11e8-95cc-c246cd608aae.jpg)

3:
![conquer_2018-02-15_13-44-40](https://user-images.githubusercontent.com/27389256/36257296-94c37710-1256-11e8-90e6-0fe911006f39.jpg)

4:
![conquer_2018-02-15_13-44-57](https://user-images.githubusercontent.com/27389256/36257301-9852abd0-1256-11e8-8daf-88793f21a94d.jpg)

**Comment by nusku-co** [comment]
The chance of an item dropping red name is (10 + PkPoints/10)% , so probably in your case around 13-15%  chance on each item of dropping.

How many times did you try killing?

**Comment by Scellow** [comment]
Oh i thought it was like around the 100%, we tried 4 times, my bad, my memory failed again ^^
