### ISSUE TITLE
Glow around glowing items doesn't seem to work in market shops

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#205]
https://i.imgur.com/DMXm3IO.png

**Comment by nusku-co** [comment]
btw, you can copy images here by directly pasting the image instead of the url like this:
![image](https://user-images.githubusercontent.com/34038364/36300285-ac4c8d36-12ce-11e8-8f12-ed284ffa5b2c.png)

**Comment by prinya801** [comment]
Yea I know that's just what I decided to do at the time, it's pretty much the same thing regardless xD

**Comment by nusku-co** [comment]
Seems this was only for dbs/mets. Has been fixed for next update
