### ISSUE TITLE
Disconnect when a player jumps too far (greater than jump distance)

### ISSUE THREAD

**Issue by nusku-co** [nusku-co/conquergods#212]

**Comment by Scellow** [comment]
Disconnect is too aggressive, you should just calculate the distance properly and not handle the packet if too far, it can happen by accident, you click one side, then quickly the other side

**Comment by nusku-co** [comment]
Yeah, I am not implementing this. Instead I fixed the jump client-side so you can't jump from side to side to increase your jump distance. Since this is no longer an issue, I'm closing it
