### ISSUE TITLE
Reduce jump distance to 18 coordinates

### ISSUE THREAD

**Issue by nusku-co** [nusku-co/conquergods#213]
The current jump distance was increased for QoL, however it causes a lot of balance issues.
The jump distance will be reduced to 18 coordinates (original was 16)

**Comment by Scellow** [comment]
I think there is a problem when you calculate the distance between two point, specially when it happens  in diagonals 

I'm able to jump super long distance by jumping from these points continously

![image](https://user-images.githubusercontent.com/27389256/36320125-6e6ec2c8-1345-11e8-8bb4-a4471c049eb0.png)

My character is currently jumping a really large distance  (he is now offscreen)

**Comment by prinya801** [comment]
I think this is what you mean?
https://www.youtube.com/watch?v=9lh75Awi7Es
