### ISSUE TITLE
Item is too far away

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#218]
Just had this happen to me, I was standing ontop of an item and tried to loot it but it said I was too far away. Something to do with desync maybe? If you click on an item it walks up to it and loots it theres no way you can be "too far away" from an item?
![image](https://user-images.githubusercontent.com/29521072/36340772-bb69e7c6-13e3-11e8-82f7-39cb05c01f85.png)

**Comment by prinya801** [comment]
I think I found the reason for this. Apparently, the item dropped isn't in the location I see on my screen. If I tab to a different client I can see the item is in a different position.

**Comment by Scellow** [comment]
Yeah there is some issues with the screen system, i had similar bug i forgot to report
![conquer_2018-02-05_17-32-32](https://user-images.githubusercontent.com/27389256/36342387-1b51ab0a-13fe-11e8-958d-af149244af0c.jpg)

![conquer_2018-02-05_17-26-35](https://user-images.githubusercontent.com/27389256/36342390-21f5d79c-13fe-11e8-8f64-39544015a168.jpg)
