### ISSUE TITLE
Ghost Guard following player after walking into a teleport or dying

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#220]
You can visually have 2 guards active if you walk into a teleport with one. It's just visually, it won't attack anything. Though it will show all the animations like jumping and attacking.
It seems to work the same way when you die. 
The guard isn't visible to other players other than the owner.
![image](https://user-images.githubusercontent.com/29521072/36347454-f37c047c-1457-11e8-8b43-d4ec19e56192.png)

**Comment by nusku-co** [comment]
This was fixed as part of another release already
