### ISSUE TITLE
MagicShield and (XP) Shield prevents the receiver from casting spells

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#226]

**Comment by nusku-co** [comment]
This is how magic/xp shield has always worked. It prevents the person who it's being casted on from receiving any other beneficial spells (like stig, etc)

**Comment by Silver0ne1** [comment]
Nusku, u got it wrong, read again what the guy said. And i wanted to add, the tao shield aswell prevents the RECEIVER to cast any spells. Like, if i cast on MYSELF, i cannot even heal team or stig the team leader anymore. Its a bug.
