### ISSUE TITLE
Using Invisibility on a creature spends the mana but doesn't apply the effect

### ISSUE THREAD

**Issue by prinya801** [nusku-co/conquergods#227]
I don't know if it should even be possible to use it on a creature. But it would be a good way to level it up.

**Comment by nusku-co** [comment]
This is how invisibility should work, it cannot be cast on anything but players

**Comment by nusku-co** [comment]
Also, yes it should use mana even if it doesn't apply the effect. That's how TQ seemed to do it as well (for whatever reason)
