### ISSUE TITLE
ANI Load Errors

### ISSUE THREAD

**Issue by nusku-co** [nusku-co/conquergods#254]
There seems to be a number of players still getting ANI load errors

As reported by HowWeDo:
![image](https://user-images.githubusercontent.com/34038364/36691855-7430f19c-1b04-11e8-95df-c80bdd362d42.png)

**Comment by prinya801** [comment]
![image](https://user-images.githubusercontent.com/29521072/36821262-4ea6f698-1cf2-11e8-8aad-d2a1f716efd9.png)
