### ISSUE TITLE
Objects disapear in TG lvl 90 spot

### ISSUE THREAD

**Issue by Scellow** [nusku-co/conquergods#38]
I walked to that spot, and all the objects disapeared

![image](https://user-images.githubusercontent.com/27389256/35333143-ee3403c8-010d-11e8-9388-393dc6a94555.png)

**Comment by nusku-co** [comment]
Seems the database I used did not have the stakes at those coordinates. Might be due to switching the TG map as well. Will take a look

**Comment by nusku-co** [comment]
Issue was with map not being updated server side. This issue is now fixed.
