### ISSUE TITLE
After a certain lvl, dbs/mets don't drop anymore in tc

### ISSUE THREAD

**Issue by BelgianWarGod** [nusku-co/conquergods#41]
Around level 40 there is no more dragonball or meteor drop in Twin City.

**Comment by nusku-co** [comment]
This is due to a feature added in later version of CO. If a person was greater than lvl 40, no mets/dbs would drop for them in TC.

However, since this was added AFTER 1.0, I am going to remove it. After next update, any players will be able to get DBs/Mets in TC.
