### ISSUE TITLE
Mining stops after a few swings

### ISSUE THREAD

**Issue by nusku-co** [nusku-co/conquergods#9]
It seems to stop after 2 swings.

User provided image: https://imgur.com/dajVWBN

**Comment by Scellow** [comment]
I'm now able to mine, i don't know why i couldn't before

**Comment by Scellow** [comment]
It happens again, i'm unable to mine

**Comment by nusku-co** [comment]
This might have something to do with the equipment bug and disappearing items.
Next time you are unable to mine, could you relog right after and see if the pick is still equipped?
